services:
  docker-api-swagger-oatpp:
    build:
      context: .
      dockerfile: Dockerfile-debian-prod
      args:
        - MAKE_PARALLEL_EXECUTION=ON  # ON/OFF
    image: docker-api-swagger-oatpp:debian
    container_name: docker-api-swagger-oatpp
    hostname: docker-api-swagger-oatpp
    restart: always
    ports:
      - 8001:8001
    environment:
      DOCKER_SERVER_IP: 192.168.88.18
      DOCKER_SERVER_PORT: 2375
    networks:
      docker-api-swagger-oatpp:

networks:
  docker-api-swagger-oatpp:
