FROM debian:bookworm-slim as base

RUN apt update && apt upgrade -y && apt install -y build-essential libcurl4-openssl-dev


FROM base as build

RUN apt install -y git cmake pkg-config

ARG MAKE_PARALLEL_EXECUTION
ENV MAKE_PARALLEL_EXECUTION $MAKE_PARALLEL_EXECUTION

COPY ./utility /app/utility

WORKDIR /app/utility

RUN bash install-oatpp-modules.sh Release

COPY ./src /app/src
COPY ./CMakeLists.txt /app

WORKDIR /app/build

RUN cmake -DCMAKE_BUILD_TYPE=Release .. && make -j $(nproc)


FROM base

COPY --from=build /app/build/docker-api-swagger-oatpp /app/build/docker-api-swagger-oatpp

COPY ./res /app/res

WORKDIR /app/build

# EXPOSE 8001

CMD ["./docker-api-swagger-oatpp"]
