FROM alpine

RUN apk update && apk upgrade && apk --no-cache add g++ gdb git make cmake pkgconfig curl-dev

ARG MAKE_PARALLEL_EXECUTION
ENV MAKE_PARALLEL_EXECUTION $MAKE_PARALLEL_EXECUTION

COPY ./utility/install-oatpp-modules-dev.sh /

WORKDIR /

RUN sh install-oatpp-modules-dev.sh Release

WORKDIR /app
