FROM debian:buster-slim

RUN apt update && apt upgrade -y && apt install -y git make cmake build-essential libcurl4-openssl-dev pkg-config

COPY ./utility /app/utility

WORKDIR /app/utility

RUN bash install-oatpp-modules.sh Release

COPY ./ /app/

WORKDIR /app/build

RUN cmake ..
RUN make -j $(nproc)

# EXPOSE 8000

ENTRYPOINT ["./docker-api-swagger"]
