FROM debian:bullseye-slim as build

RUN apt update && apt upgrade -y && apt install -y git cmake build-essential libcurl4-openssl-dev pkg-config

ARG MAKE_PARALLEL_EXECUTION
ENV MAKE_PARALLEL_EXECUTION $MAKE_PARALLEL_EXECUTION

COPY ./utility /app/utility

WORKDIR /app/utility

RUN bash install-oatpp-modules.sh Release

COPY ./src /app/src
COPY ./CMakeLists.txt /app

WORKDIR /app/build

RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make -j $(nproc)


FROM debian:bullseye-slim

RUN apt update && apt upgrade -y && apt install -y build-essential libcurl4-openssl-dev

COPY --from=build /app/build/docker-api-swagger /app/build/docker-api-swagger

COPY ./res /app/res

WORKDIR /app/build

# EXPOSE 8001

CMD ["./docker-api-swagger"]
