FROM alpine:3.19 as base

RUN apk update && apk upgrade && apk --no-cache add g++


FROM base as build

RUN apk --no-cache add git make cmake pkgconfig curl-dev

ARG MAKE_PARALLEL_EXECUTION
ENV MAKE_PARALLEL_EXECUTION $MAKE_PARALLEL_EXECUTION

COPY ./utility /app/utility

WORKDIR /app/utility

RUN sh install-oatpp-modules.sh Release

COPY ./src /app/src
COPY ./CMakeLists.txt /app

WORKDIR /app/build

RUN cmake -DCMAKE_BUILD_TYPE=Release .. && make -j $(nproc)


FROM base

COPY --from=build /app/build/docker-api-swagger-oatpp /app/build/docker-api-swagger-oatpp

COPY ./res /app/res

WORKDIR /app/build

CMD ["./docker-api-swagger-oatpp"]
