FROM alpine

RUN apk update && apk upgrade && apk --no-cache add g++ git make cmake pkgconfig curl-dev

ARG MAKE_PARALLEL_EXECUTION
ENV MAKE_PARALLEL_EXECUTION $MAKE_PARALLEL_EXECUTION

COPY ./utility /app/utility

WORKDIR /app/utility

RUN sh install-oatpp-modules.sh Release
