version: '3.8'

services:
  docker-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile-alpine-3.13
      args:
        - MAKE_PARALLEL_EXECUTION=OFF  # ON/OFF
    image: docker-api-swagger:alpine-3.13
    container_name: docker-api-swagger
    hostname: docker-api-swagger
    restart: always
    ports:
      - 8001:8001
    environment:
      DOCKER_SERVER_IP: 192.168.88.8
      DOCKER_SERVER_PORT: 2375
    networks:
      docker-api-swagger:
  
networks:
  docker-api-swagger:
